"""
Script to populate the database with products and representatives
"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv
from pathlib import Path
import uuid

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]

# Storage recommendations by product type
STORAGE_INFO = {
    "peptide": "Store lyophilized peptides at -20°C. Once reconstituted, store at 2-8°C and use within 30 days. Avoid freeze-thaw cycles.",
    "glp1": "Store at -20°C before reconstitution. After reconstitution, refrigerate at 2-8°C and use within 28 days. Do not freeze after reconstitution.",
    "nootropic": "Store in a cool, dry place away from direct sunlight. Keep container tightly closed. Room temperature (15-25°C) is acceptable.",
    "coenzyme": "Store in a cool, dry place at room temperature (15-25°C). Protect from light and moisture. Keep away from heat sources.",
    "extract": "Store in a cool, dry place away from direct sunlight. Keep tightly sealed. Refrigeration is optional but extends shelf life."
}

async def seed_products():
    """Seed all products"""
    
    products = [
        # GLP-1 Analogs
        {
            "id": str(uuid.uuid4()),
            "name": "Tirzepatide 10mg",
            "category": "GLP-1 Analogs",
            "product_type": "Tirzepatide",
            "purity": "99% HPLC",
            "dosage": "10mg",
            "description": "Dual GIP and GLP-1 receptor agonist for metabolic research. High-purity compound for advanced studies.",
            "price": 89.99,
            "verification_code": "ZX-ZE101208",
            "storage_info": STORAGE_INFO["glp1"],
            "batch_number": "RX-2025-TZ10-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Tirzepatide 15mg",
            "category": "GLP-1 Analogs",
            "product_type": "Tirzepatide",
            "purity": "99% HPLC",
            "dosage": "15mg",
            "description": "Dual GIP and GLP-1 receptor agonist for metabolic research. Enhanced dosage for extended studies.",
            "price": 119.99,
            "verification_code": "ZX-ZE151021",
            "storage_info": STORAGE_INFO["glp1"],
            "batch_number": "RX-2025-TZ15-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Tirzepatide 20mg",
            "category": "GLP-1 Analogs",
            "product_type": "Tirzepatide",
            "purity": "99% HPLC",
            "dosage": "20mg",
            "description": "Dual GIP and GLP-1 receptor agonist for metabolic research. Maximum concentration for intensive research protocols.",
            "price": 149.99,
            "verification_code": "ZX-ZE200923",
            "storage_info": STORAGE_INFO["glp1"],
            "batch_number": "RX-2025-TZ20-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Retatrutide 10mg",
            "category": "GLP-1 Analogs",
            "product_type": "Retatrutide",
            "purity": "99% HPLC",
            "dosage": "10mg",
            "description": "Triple GIP, GLP-1 and glucagon receptor agonist for advanced metabolic research studies.",
            "price": 109.99,
            "verification_code": "ZX-RE101210",
            "storage_info": STORAGE_INFO["glp1"],
            "batch_number": "RX-2025-RT10-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Retatrutide 15mg",
            "category": "GLP-1 Analogs",
            "product_type": "Retatrutide",
            "purity": "99% HPLC",
            "dosage": "15mg",
            "description": "Triple GIP, GLP-1 and glucagon receptor agonist. Enhanced concentration for extended research protocols.",
            "price": 139.99,
            "verification_code": "ZX-RE151128",
            "storage_info": STORAGE_INFO["glp1"],
            "batch_number": "RX-2025-RT15-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        
        # Research Peptides
        {
            "id": str(uuid.uuid4()),
            "name": "BPC-157 5mg",
            "category": "Research Peptides",
            "product_type": "BPC-157",
            "purity": "99% HPLC",
            "dosage": "5mg",
            "description": "Body Protection Compound pentadecapeptide with regenerative properties for tissue repair research.",
            "price": 39.99,
            "verification_code": "ZX-BP050823",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-BP05-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "BPC-157 10mg",
            "category": "Research Peptides",
            "product_type": "BPC-157",
            "purity": "99% HPLC",
            "dosage": "10mg",
            "description": "Body Protection Compound pentadecapeptide. Enhanced dosage for comprehensive tissue repair studies.",
            "price": 69.99,
            "verification_code": "ZX-BP100714",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-BP10-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "TB-500 2mg",
            "category": "Research Peptides",
            "product_type": "TB-500",
            "purity": "99% HPLC",
            "dosage": "2mg",
            "description": "Thymosin beta-4 fragment for tissue repair and regeneration research applications.",
            "price": 29.99,
            "verification_code": "ZX-TB020916",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-TB02-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "TB-500 5mg",
            "category": "Research Peptides",
            "product_type": "TB-500",
            "purity": "99% HPLC",
            "dosage": "5mg",
            "description": "Thymosin beta-4 fragment. Enhanced concentration for advanced tissue repair research.",
            "price": 49.99,
            "verification_code": "ZX-TB050327",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-TB05-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "CJC-1295 2mg",
            "category": "Research Peptides",
            "product_type": "CJC-1295",
            "purity": "99% HPLC",
            "dosage": "2mg",
            "description": "Growth hormone releasing hormone analog for endocrine system research studies.",
            "price": 29.99,
            "verification_code": "ZX-CJ020501",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-CJ02-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "CJC-1295 5mg",
            "category": "Research Peptides",
            "product_type": "CJC-1295",
            "purity": "99% HPLC",
            "dosage": "5mg",
            "description": "Growth hormone releasing hormone analog. Higher concentration for extended research protocols.",
            "price": 49.99,
            "verification_code": "ZX-CJ050312",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-CJ05-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Ipamorelin 2mg",
            "category": "Research Peptides",
            "product_type": "Ipamorelin",
            "purity": "99% HPLC",
            "dosage": "2mg",
            "description": "Growth hormone secretagogue for research on growth hormone release mechanisms.",
            "price": 24.99,
            "verification_code": "ZX-IP020715",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-IP02-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Ipamorelin 5mg",
            "category": "Research Peptides",
            "product_type": "Ipamorelin",
            "purity": "99% HPLC",
            "dosage": "5mg",
            "description": "Growth hormone secretagogue. Enhanced dosage for comprehensive endocrine research.",
            "price": 39.99,
            "verification_code": "ZX-IP050128",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-IP05-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Epithalon 10mg",
            "category": "Research Peptides",
            "product_type": "Epithalon",
            "purity": "99% HPLC",
            "dosage": "10mg",
            "description": "Telomerase activator peptide for aging and longevity research applications.",
            "price": 49.99,
            "verification_code": "ZX-EP100101",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-EP10-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Epithalon 50mg",
            "category": "Research Peptides",
            "product_type": "Epithalon",
            "purity": "99% HPLC",
            "dosage": "50mg",
            "description": "Telomerase activator peptide. Bulk quantity for extensive longevity research studies.",
            "price": 199.99,
            "verification_code": "ZX-EP500523",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-EP50-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "MOTS-c 10mg",
            "category": "Research Peptides",
            "product_type": "MOTS-c",
            "purity": "99% HPLC",
            "dosage": "10mg",
            "description": "Mitochondrial-derived peptide for metabolic regulation and cellular energy research.",
            "price": 79.99,
            "verification_code": "ZX-MC100429",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-MC10-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "PT-141 10mg",
            "category": "Research Peptides",
            "product_type": "PT-141",
            "purity": "99% HPLC",
            "dosage": "10mg",
            "description": "Melanocortin receptor agonist for research on melanocortin pathways and receptor interactions.",
            "price": 59.99,
            "verification_code": "ZX-PT101215",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-PT10-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Tesamorelin 2mg",
            "category": "Research Peptides",
            "product_type": "Tesamorelin",
            "purity": "99% HPLC",
            "dosage": "2mg",
            "description": "Growth hormone releasing hormone analog for research on lipid metabolism and body composition.",
            "price": 89.99,
            "verification_code": "ZX-TE020830",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-TE02-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        
        # Cognitive Enhancers (Nootropics)
        {
            "id": str(uuid.uuid4()),
            "name": "Semax 3mg",
            "category": "Cognitive Enhancers",
            "product_type": "Semax",
            "purity": "99% HPLC",
            "dosage": "3mg",
            "description": "Neuroprotective peptide with nootropic effects for cognitive enhancement research.",
            "price": 34.99,
            "verification_code": "ZX-SE030409",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-SE03-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Semax 5mg",
            "category": "Cognitive Enhancers",
            "product_type": "Semax",
            "purity": "99% HPLC",
            "dosage": "5mg",
            "description": "Neuroprotective peptide. Enhanced concentration for extended cognitive research studies.",
            "price": 44.99,
            "verification_code": "ZX-SE050322",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-SE05-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Selank 3mg",
            "category": "Cognitive Enhancers",
            "product_type": "Selank",
            "purity": "99% HPLC",
            "dosage": "3mg",
            "description": "Anxiolytic peptide with nootropic properties for stress and anxiety research.",
            "price": 32.99,
            "verification_code": "ZX-SL030518",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-SL03-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Selank 5mg",
            "category": "Cognitive Enhancers",
            "product_type": "Selank",
            "purity": "99% HPLC",
            "dosage": "5mg",
            "description": "Anxiolytic peptide. Higher dosage for comprehensive neurological research protocols.",
            "price": 42.99,
            "verification_code": "ZX-SL050611",
            "storage_info": STORAGE_INFO["peptide"],
            "batch_number": "RX-2025-SL05-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Noopept 10mg",
            "category": "Cognitive Enhancers",
            "product_type": "Noopept",
            "purity": "99% HPLC",
            "dosage": "10mg",
            "description": "Synthetic nootropic peptide for cognitive research and memory enhancement studies.",
            "price": 19.99,
            "verification_code": "ZX-NO010018",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-NO10-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Noopept 100mg",
            "category": "Cognitive Enhancers",
            "product_type": "Noopept",
            "purity": "99% HPLC",
            "dosage": "100mg",
            "description": "Synthetic nootropic peptide. Bulk quantity for extensive cognitive research applications.",
            "price": 79.99,
            "verification_code": "ZX-NO100019",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-NO100-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Modafinil 100mg",
            "category": "Cognitive Enhancers",
            "product_type": "Modafinil",
            "purity": "99% HPLC",
            "dosage": "100mg",
            "description": "Wakefulness-promoting agent for sleep disorder and cognitive enhancement research.",
            "price": 49.99,
            "verification_code": "ZX-MO010023",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-MO100-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Modafinil 1g",
            "category": "Cognitive Enhancers",
            "product_type": "Modafinil",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Wakefulness-promoting agent. Bulk quantity for comprehensive sleep research protocols.",
            "price": 299.99,
            "verification_code": "ZX-MO100024",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-MO1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Alpha-GPC 100mg",
            "category": "Cognitive Enhancers",
            "product_type": "Alpha-GPC",
            "purity": "99% HPLC",
            "dosage": "100mg",
            "description": "Cholinergic compound for cognitive research and acetylcholine pathway studies.",
            "price": 19.99,
            "verification_code": "ZX-AG010011",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-AG100-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Alpha-GPC 1g",
            "category": "Cognitive Enhancers",
            "product_type": "Alpha-GPC",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Cholinergic compound. Bulk quantity for extensive neurotransmitter research.",
            "price": 89.99,
            "verification_code": "ZX-AG100012",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-AG1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "L-Theanine 100mg",
            "category": "Cognitive Enhancers",
            "product_type": "L-Theanine",
            "purity": "99% HPLC",
            "dosage": "100mg",
            "description": "Amino acid from green tea for relaxation and stress response research.",
            "price": 14.99,
            "verification_code": "ZX-LT010016",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-LT100-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "L-Theanine 1g",
            "category": "Cognitive Enhancers",
            "product_type": "L-Theanine",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Amino acid from green tea. Bulk quantity for comprehensive relaxation research.",
            "price": 49.99,
            "verification_code": "ZX-LT100017",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-LT1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Lion's Mane Extract 500mg",
            "category": "Cognitive Enhancers",
            "product_type": "Lion's Mane",
            "purity": "30% polysaccharides",
            "dosage": "500mg",
            "description": "Hericium erinaceus extract for neural research and nerve growth factor studies.",
            "price": 29.99,
            "verification_code": "ZX-LM050013",
            "storage_info": STORAGE_INFO["extract"],
            "batch_number": "RX-2025-LM500-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Lion's Mane Extract 1g",
            "category": "Cognitive Enhancers",
            "product_type": "Lion's Mane",
            "purity": "30% polysaccharides",
            "dosage": "1g",
            "description": "Hericium erinaceus extract. Enhanced quantity for extended neurological research.",
            "price": 49.99,
            "verification_code": "ZX-LM100014",
            "storage_info": STORAGE_INFO["extract"],
            "batch_number": "RX-2025-LM1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Bacopa Monnieri Extract 500mg",
            "category": "Cognitive Enhancers",
            "product_type": "Bacopa Monnieri",
            "purity": "20% bacosides",
            "dosage": "500mg",
            "description": "Ayurvedic herb extract for cognitive function and memory research applications.",
            "price": 24.99,
            "verification_code": "ZX-BM050015",
            "storage_info": STORAGE_INFO["extract"],
            "batch_number": "RX-2025-BM500-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Phenibut HCl 1g",
            "category": "Cognitive Enhancers",
            "product_type": "Phenibut",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "GABA analog for neurological research and anxiolytic mechanism studies.",
            "price": 29.99,
            "verification_code": "ZX-PH100020",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-PH1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Phenibut HCl 10g",
            "category": "Cognitive Enhancers",
            "product_type": "Phenibut",
            "purity": "99% HPLC",
            "dosage": "10g",
            "description": "GABA analog. Bulk quantity for comprehensive neurological research protocols.",
            "price": 199.99,
            "verification_code": "ZX-PH100021",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-PH10G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Tianeptine Sodium 1g",
            "category": "Cognitive Enhancers",
            "product_type": "Tianeptine",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Atypical antidepressant compound for neurological and mood disorder research.",
            "price": 39.99,
            "verification_code": "ZX-TI100022",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-TI1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Kava Extract 500mg",
            "category": "Cognitive Enhancers",
            "product_type": "Kava",
            "purity": "30% kavalactones",
            "dosage": "500mg",
            "description": "Piper methysticum extract for anxiety research and GABAergic pathway studies.",
            "price": 34.99,
            "verification_code": "ZX-KA050025",
            "storage_info": STORAGE_INFO["extract"],
            "batch_number": "RX-2025-KA500-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "5-HTP 100mg",
            "category": "Cognitive Enhancers",
            "product_type": "5-HTP",
            "purity": "99% HPLC",
            "dosage": "100mg",
            "description": "Serotonin precursor for mood research and neurotransmitter synthesis studies.",
            "price": 24.99,
            "verification_code": "ZX-5H010026",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-5H100-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "5-HTP 1g",
            "category": "Cognitive Enhancers",
            "product_type": "5-HTP",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Serotonin precursor. Bulk quantity for extensive mood disorder research.",
            "price": 99.99,
            "verification_code": "ZX-5H100027",
            "storage_info": STORAGE_INFO["nootropic"],
            "batch_number": "RX-2025-5H1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        
        # Coenzymes
        {
            "id": str(uuid.uuid4()),
            "name": "NAD+ 100mg",
            "category": "Coenzymes",
            "product_type": "NAD+",
            "purity": "99% HPLC",
            "dosage": "100mg",
            "description": "Nicotinamide adenine dinucleotide coenzyme central to cellular metabolism research.",
            "price": 49.99,
            "verification_code": "ZX-NA010003",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-NA100-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "NAD+ 1g",
            "category": "Coenzymes",
            "product_type": "NAD+",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Nicotinamide adenine dinucleotide. Bulk quantity for comprehensive metabolism studies.",
            "price": 199.99,
            "verification_code": "ZX-NA100004",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-NA1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "NMN 1g",
            "category": "Coenzymes",
            "product_type": "NMN",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Nicotinamide mononucleotide NAD+ precursor for cellular energy and aging research.",
            "price": 39.99,
            "verification_code": "ZX-NM010005",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-NM1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": True
        },
        {
            "id": str(uuid.uuid4()),
            "name": "NMN 10g",
            "category": "Coenzymes",
            "product_type": "NMN",
            "purity": "99% HPLC",
            "dosage": "10g",
            "description": "Nicotinamide mononucleotide. Bulk quantity for extensive longevity research protocols.",
            "price": 299.99,
            "verification_code": "ZX-NM100006",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-NM10G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Nicotinamide Riboside 1g",
            "category": "Coenzymes",
            "product_type": "NR",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "NAD+ precursor with high bioavailability for cellular energy metabolism research.",
            "price": 44.99,
            "verification_code": "ZX-NR010007",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-NR1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Nicotinamide Riboside 10g",
            "category": "Coenzymes",
            "product_type": "NR",
            "purity": "99% HPLC",
            "dosage": "10g",
            "description": "NAD+ precursor. Bulk quantity for comprehensive cellular metabolism studies.",
            "price": 349.99,
            "verification_code": "ZX-NR100008",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-NR10G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Coenzyme Q10 100mg",
            "category": "Coenzymes",
            "product_type": "CoQ10",
            "purity": "99% HPLC",
            "dosage": "100mg",
            "description": "Electron carrier in mitochondrial electron transport chain research applications.",
            "price": 24.99,
            "verification_code": "ZX-CQ010009",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-CQ100-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Coenzyme Q10 1g",
            "category": "Coenzymes",
            "product_type": "CoQ10",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Electron carrier. Bulk quantity for extensive mitochondrial function research.",
            "price": 149.99,
            "verification_code": "ZX-CQ100010",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-CQ1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Adenosine 1g",
            "category": "Coenzymes",
            "product_type": "Adenosine",
            "purity": "99% HPLC",
            "dosage": "1g",
            "description": "Nucleoside involved in cellular energy transfer and ATP synthesis research.",
            "price": 29.99,
            "verification_code": "ZX-AD100001",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-AD1G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Adenosine 5g",
            "category": "Coenzymes",
            "product_type": "Adenosine",
            "purity": "99% HPLC",
            "dosage": "5g",
            "description": "Nucleoside. Bulk quantity for comprehensive cellular energy research protocols.",
            "price": 99.99,
            "verification_code": "ZX-AD500002",
            "storage_info": STORAGE_INFO["coenzyme"],
            "batch_number": "RX-2025-AD5G-001",
            "manufacturing_date": "2025-01-15",
            "expiry_date": "2027-01-15",
            "coa_url": "#",
            "featured": False
        },
    ]
    
    # Clear existing products
    await db.products.delete_many({})
    
    # Insert all products
    if products:
        await db.products.insert_many(products)
        print(f"✅ Successfully seeded {len(products)} products")
    
    return len(products)

async def seed_representatives():
    """Seed representatives"""
    
    representatives = [
        {
            "id": str(uuid.uuid4()),
            "country": "Paraguay",
            "region": "South America",
            "name": "Carlos Rodriguez",
            "whatsapp": "+595123456789",
            "flag_emoji": "🇵🇾"
        },
        {
            "id": str(uuid.uuid4()),
            "country": "United States",
            "region": "North America",
            "name": "Michael Johnson",
            "whatsapp": "+15551234567",
            "flag_emoji": "🇺🇸"
        },
        {
            "id": str(uuid.uuid4()),
            "country": "Hong Kong",
            "region": "Asia",
            "name": "Wei Chen",
            "whatsapp": "+85212345678",
            "flag_emoji": "🇭🇰"
        }
    ]
    
    # Clear existing representatives
    await db.representatives.delete_many({})
    
    # Insert representatives
    if representatives:
        await db.representatives.insert_many(representatives)
        print(f"✅ Successfully seeded {len(representatives)} representatives")
    
    return len(representatives)

async def main():
    """Main seeding function"""
    print("🌱 Starting database seeding...")
    
    try:
        products_count = await seed_products()
        reps_count = await seed_representatives()
        
        print(f"\n✅ Database seeding completed successfully!")
        print(f"   - {products_count} products")
        print(f"   - {reps_count} representatives")
        
    except Exception as e:
        print(f"❌ Error seeding database: {e}")
    finally:
        client.close()

if __name__ == "__main__":
    asyncio.run(main())
