"""Seed Stack Hubs for the 20 peptides that had no protocol hub.
Idempotent upsert by slug. Same schema/pattern as seed_new_hubs.py.
Slugs/peptide_names chosen so the product->hub matcher (normalized substring,
longest-match) links each product correctly without colliding with existing hubs.
"""
import asyncio
import os
import uuid
from pathlib import Path

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv(Path(__file__).resolve().parent.parent / ".env")


def proto(order, name, goal, compounds, steps, best_for, duration):
    return {"id": str(uuid.uuid4()), "order": order, "name": name, "goal": goal,
            "compounds": compounds, "protocol": steps, "best_for": best_for, "duration": duration}


HUBS = [
    # ───────────────────────── GH / SECRETAGOGUES ─────────────────────────
    {
        "slug": "hgh", "peptide_slug": "hgh", "peptide_name": "HGH",
        "title": "HGH Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "GH / Secretagogues", "category_slug": "gh-secretagogues",
        "classification": "Recombinant Human Growth Hormone (Somatropin, 191aa)",
        "also_known_as": ["Somatropin", "rHGH", "GH"],
        "description": "Recombinant human growth hormone (somatropin) is the reference GH peptide researched for recovery, body composition, connective-tissue quality and sleep. Because it acts directly on GH receptors and IGF-1 output, dosing is conservative and timing-sensitive.",
        "core_info": {
            "function": "Recovery, fat metabolism, lean tissue support, sleep and skin quality.",
            "typical_dosage": "1–3 IU daily (research), split or single dose",
            "administration": "Subcutaneous injection (reconstituted)",
            "best_timing": "Morning fasted, or post-workout / pre-bed",
            "common_cycle": "8–16+ weeks, 5 days on / 2 off common",
            "common_pairings": ["CJC-1295 + Ipamorelin", "Ipamorelin", "MOTS-c", "Glutathione"],
        },
        "protocols": [
            proto(1, "Foundational Recovery Protocol", "Introductory GH exposure for recovery and sleep.",
                  [{"name": "HGH", "dose": "1–2 IU SC once daily"}],
                  ["Reconstitute the 10 IU vial with 1 mL bacteriostatic water (1 IU = 0.1 mL).",
                   "Inject 1–2 IU SC each morning fasted, 5 days on / 2 off.",
                   "Assess sleep depth and recovery at week 4 before adjusting.",
                   "Store reconstituted vial at 2–8°C, use within 14–21 days."],
                  "First-time GH research, recovery focus", "8–12 weeks"),
            proto(2, "GH Pulse Amplifier Stack", "Combine exogenous GH with a secretagogue for a natural release pattern.",
                  [{"name": "HGH", "dose": "2 IU AM"},
                   {"name": "CJC-1295 + Ipamorelin", "dose": "300/300 mcg SC pre-bed"}],
                  ["HGH 2 IU SC on waking (fasted).",
                   "CJC/Ipa blend before bed on an empty stomach (2h after food).",
                   "Keep carbs low around each injection to reduce blunting from insulin.",
                   "Run 5 days on / 2 off."],
                  "Amplifying endogenous GH pulses", "12 weeks"),
            proto(3, "Body Recomposition Protocol", "Fat loss with lean-tissue support during a deficit.",
                  [{"name": "HGH", "dose": "2–3 IU split AM/pre-cardio"},
                   {"name": "MOTS-c", "dose": "5 mg SC 2x/week"}],
                  ["Split HGH: 1.5 IU on waking, 1.5 IU pre-fasted cardio.",
                   "MOTS-c Monday/Thursday mornings.",
                   "Protein ≥2 g/kg; resistance training 3–4x/week.",
                   "Reassess bodyfat every 4 weeks."],
                  "Recomposition phases", "12–16 weeks"),
            proto(4, "Connective Tissue & Skin Protocol", "Collagen, tendon and skin-quality emphasis.",
                  [{"name": "HGH", "dose": "1.5 IU daily"},
                   {"name": "BPC-157", "dose": "250 mcg SC daily"}],
                  ["HGH 1.5 IU each morning.",
                   "BPC-157 250 mcg SC near the area of interest.",
                   "Prioritize 7.5h+ sleep — GH benefits track with deep sleep.",
                   "SPF daily for skin-focused runs."],
                  "Tendon, joint and skin-quality goals", "8–12 weeks"),
        ],
    },
    {
        "slug": "hgh-176-191", "peptide_slug": "hgh-176-191", "peptide_name": "HGH Fragment 176-191",
        "title": "HGH Fragment 176-191 Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "GH / Secretagogues", "category_slug": "gh-secretagogues",
        "classification": "C-terminal GH Fragment (Lipolytic, aa 176-191)",
        "also_known_as": ["HGH Frag", "Frag 176-191", "AOD analog"],
        "description": "HGH Fragment 176-191 is the lipolytic C-terminal region of growth hormone, researched for targeted fat metabolism without the systemic IGF-1 effects of full GH. It stimulates lipolysis and inhibits lipogenesis while sparing glucose handling.",
        "core_info": {
            "function": "Targeted fat metabolism (lipolysis) without full-GH systemic effects.",
            "typical_dosage": "250–500 mcg 1–2x daily",
            "administration": "Subcutaneous injection (fasted)",
            "best_timing": "Fasted AM and/or pre-cardio",
            "common_cycle": "8–12 weeks",
            "common_pairings": ["Retatrutide", "Tirzepatide", "MOTS-c", "5-Amino-1MQ"],
        },
        "protocols": [
            proto(1, "Fasted Lipolysis Protocol", "Baseline fat-metabolism protocol timed to fasting.",
                  [{"name": "HGH Fragment 176-191", "dose": "250 mcg SC 2x daily fasted"}],
                  ["Reconstitute 5 mg vial with 2 mL bacteriostatic water (250 mcg = 0.1 mL).",
                   "Inject 250 mcg on waking; wait 20–30 min before eating.",
                   "Second 250 mcg pre-fasted cardio (or mid-afternoon fasted).",
                   "Keep the injection window low-carb to maximize lipolysis."],
                  "Targeted fat metabolism research", "8–12 weeks"),
            proto(2, "Cardio Accelerator Stack", "Pair with fasted LISS for stubborn fat areas.",
                  [{"name": "HGH Fragment 176-191", "dose": "300 mcg pre-cardio"}],
                  ["Inject 300 mcg 20–30 min before fasted low-intensity cardio.",
                   "30–45 min LISS 4–5x/week.",
                   "Delay first meal 60 min post-cardio when practical.",
                   "Hydrate and replace electrolytes."],
                  "Stubborn/regional fat during a cut", "8–10 weeks"),
            proto(3, "GLP-1 Fat-Loss Companion", "Add lipolytic drive to an incretin protocol.",
                  [{"name": "HGH Fragment 176-191", "dose": "250 mcg 2x daily"},
                   {"name": "Retatrutide or Tirzepatide", "dose": "per ongoing protocol"}],
                  ["Continue the weekly GLP-1 dose unchanged.",
                   "Add Frag 250 mcg AM fasted and pre-cardio.",
                   "Maintain protein high to protect lean mass.",
                   "Reassess at week 6."],
                  "Enhancing an existing GLP-1 cut", "8–12 weeks"),
            proto(4, "Recomp Energy Stack", "Fat metabolism with mitochondrial support.",
                  [{"name": "HGH Fragment 176-191", "dose": "250 mcg 2x daily"},
                   {"name": "MOTS-c", "dose": "5 mg SC 2x/week"}],
                  ["Frag AM fasted + pre-cardio.",
                   "MOTS-c Mon/Thu mornings.",
                   "Resistance training 3x/week; steps 8–10k daily."],
                  "Recomposition with energy support", "8–12 weeks"),
        ],
    },
    {
        "slug": "sermorelin", "peptide_slug": "sermorelin", "peptide_name": "Sermorelin",
        "title": "Sermorelin Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "GH / Secretagogues", "category_slug": "gh-secretagogues",
        "classification": "Growth Hormone Releasing Hormone Analog (GHRH 1-29)",
        "also_known_as": ["GRF 1-29", "Sermorelin Acetate"],
        "description": "Sermorelin is a GHRH analog that stimulates the pituitary to produce and release its own growth hormone in a natural pulsatile pattern. Researched for recovery, sleep quality and gradual body-composition support with a favorable safety profile.",
        "core_info": {
            "function": "Stimulates endogenous GH release for recovery, sleep and body composition.",
            "typical_dosage": "200–500 mcg pre-bed",
            "administration": "Subcutaneous injection",
            "best_timing": "Before bed on an empty stomach",
            "common_cycle": "12–24 weeks",
            "common_pairings": ["Ipamorelin", "CJC-1295", "MOTS-c", "Vitamin B12"],
        },
        "protocols": [
            proto(1, "Nightly Sleep & Recovery Protocol", "Support natural GH pulse during deep sleep.",
                  [{"name": "Sermorelin", "dose": "300 mcg SC nightly"}],
                  ["Reconstitute vial with bacteriostatic water per label concentration.",
                   "Inject 300 mcg SC before bed, ≥2h after last meal.",
                   "Avoid high-carb/fat meals close to injection (insulin blunts GH).",
                   "Run 5 nights on / 2 off; assess sleep and recovery at week 4."],
                  "Sleep quality and recovery", "12–16 weeks"),
            proto(2, "GHRH + GHRP Synergy Stack", "Combine GHRH with a ghrelin-mimetic for a stronger pulse.",
                  [{"name": "Sermorelin", "dose": "300 mcg nightly"},
                   {"name": "Ipamorelin", "dose": "300 mcg nightly"}],
                  ["Draw both peptides and inject together pre-bed (empty stomach).",
                   "Keep the 2h fasted window before and 30 min after.",
                   "5 nights on / 2 off.",
                   "Reassess at week 6."],
                  "Maximizing endogenous GH release", "12 weeks"),
            proto(3, "Body Composition Support Stack", "Gradual recomposition via natural GH support.",
                  [{"name": "Sermorelin", "dose": "300 mcg nightly"},
                   {"name": "MOTS-c", "dose": "5 mg 2x/week"}],
                  ["Sermorelin nightly.",
                   "MOTS-c Mon/Thu mornings.",
                   "Resistance training 3x/week; protein ≥1.8 g/kg.",
                   "Track waist and strength every 4 weeks."],
                  "Gradual recomposition", "16 weeks"),
            proto(4, "Vitality & Energy Stack", "Recovery plus energy metabolism support.",
                  [{"name": "Sermorelin", "dose": "300 mcg nightly"},
                   {"name": "Vitamin B12", "dose": "1,000 mcg SC weekly"}],
                  ["Sermorelin nightly per protocol.",
                   "B12 1,000 mcg once weekly (morning).",
                   "Prioritize sleep hygiene; limit alcohol.",
                   "Assess energy and mood at week 4."],
                  "Recovery, energy and general vitality", "12 weeks"),
        ],
    },
    # ───────────────────────── METABOLISM / LONGEVITY ─────────────────────────
    {
        "slug": "nad", "peptide_slug": "nad", "peptide_name": "NAD+",
        "title": "NAD+ Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Metabolism / Longevity", "category_slug": "metabolism-longevity",
        "classification": "Nicotinamide Adenine Dinucleotide (Coenzyme)",
        "also_known_as": ["Nicotinamide Adenine Dinucleotide"],
        "description": "NAD+ is a central coenzyme in cellular energy production and DNA repair. Levels decline with age; injectable NAD+ is researched for mitochondrial function, energy, cognitive clarity and cellular repair pathways (sirtuins, PARPs).",
        "core_info": {
            "function": "Mitochondrial energy, DNA repair, cellular longevity signaling.",
            "typical_dosage": "50–100 mg SC 2–3x/week (titrate up slowly)",
            "administration": "Subcutaneous injection (slow) or IM",
            "best_timing": "Morning (can be energizing)",
            "common_cycle": "Continuous or 8–12 week blocks",
            "common_pairings": ["MOTS-c", "Vitamin B12", "Glutathione", "5-Amino-1MQ"],
        },
        "protocols": [
            proto(1, "Gentle Introduction Protocol", "Build tolerance to NAD+ with minimal flushing.",
                  [{"name": "NAD+", "dose": "50 mg SC 2x/week, titrate to 100 mg"}],
                  ["Reconstitute per label; start at 50 mg.",
                   "Inject SLOWLY over 30–60s to reduce flushing/nausea.",
                   "Monday and Thursday mornings.",
                   "Increase to 100 mg after 2 weeks if well tolerated."],
                  "First-time NAD+ research", "8 weeks"),
            proto(2, "Cellular Energy Stack", "Mitochondrial output and daily energy.",
                  [{"name": "NAD+", "dose": "100 mg SC 3x/week"},
                   {"name": "MOTS-c", "dose": "5 mg SC 2x/week"}],
                  ["NAD+ Mon/Wed/Fri mornings (slow injection).",
                   "MOTS-c Mon/Thu.",
                   "Time on training days for perceived energy.",
                   "Hydrate well; assess energy at week 4."],
                  "Energy and mitochondrial support", "8–12 weeks"),
            proto(3, "Longevity & Repair Stack", "Cellular repair and methylation support.",
                  [{"name": "NAD+", "dose": "100 mg SC 2x/week"},
                   {"name": "Vitamin B12", "dose": "1,000 mcg weekly"},
                   {"name": "Glutathione", "dose": "200 mg 2x/week"}],
                  ["NAD+ Mon/Thu; B12 weekly; Glutathione Tue/Fri.",
                   "Separate syringes for each compound.",
                   "Consistent sleep and hydration.",
                   "Run 12 weeks, then reassess."],
                  "Longevity and cellular repair focus", "12 weeks"),
            proto(4, "Cognitive Clarity Stack", "Mental energy and focus support.",
                  [{"name": "NAD+", "dose": "100 mg 2x/week"},
                   {"name": "Semax", "dose": "300 mcg intranasal daily"}],
                  ["NAD+ Mon/Thu mornings.",
                   "Semax daily on workdays.",
                   "Assess focus and mood at week 4."],
                  "Mental clarity and focus", "8 weeks"),
        ],
    },
    {
        "slug": "5-amino-1mq", "peptide_slug": "5-amino-1mq", "peptide_name": "5-Amino-1MQ",
        "title": "5-Amino-1MQ Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Metabolism / Longevity", "category_slug": "metabolism-longevity",
        "classification": "NNMT Inhibitor (Small Molecule)",
        "also_known_as": ["5-Amino-1-methylquinolinium"],
        "description": "5-Amino-1MQ is an NNMT (nicotinamide N-methyltransferase) inhibitor researched for fat metabolism, NAD+ preservation and metabolic efficiency in adipose tissue. Oral bioavailability makes it a convenient metabolic adjunct.",
        "core_info": {
            "function": "Inhibits NNMT to support fat metabolism and preserve cellular NAD+.",
            "typical_dosage": "50–150 mg orally once daily",
            "administration": "Oral capsule",
            "best_timing": "Morning with or without food",
            "common_cycle": "8–12 weeks",
            "common_pairings": ["Tirzepatide", "Retatrutide", "MOTS-c", "NAD+"],
        },
        "protocols": [
            proto(1, "Metabolic Efficiency Protocol", "Baseline daily dosing for fat metabolism.",
                  [{"name": "5-Amino-1MQ", "dose": "50 mg oral once daily"}],
                  ["Take 50 mg each morning.",
                   "Increase to 100 mg after 2 weeks if tolerated.",
                   "Pair with resistance training 3x/week.",
                   "Protein ≥1.8 g/kg; assess at week 4."],
                  "General metabolic support", "8–12 weeks"),
            proto(2, "GLP-1 Recomp Companion", "Preserve lean mass and metabolic rate during a GLP-1 cut.",
                  [{"name": "5-Amino-1MQ", "dose": "100 mg daily"},
                   {"name": "Tirzepatide or Retatrutide", "dose": "per ongoing protocol"}],
                  ["Take 100 mg each morning alongside the weekly GLP-1.",
                   "Prioritize protein and lifting to protect muscle.",
                   "Reassess body composition every 4 weeks."],
                  "Muscle/metabolic preservation on GLP-1s", "12 weeks"),
            proto(3, "NAD+ Preservation Stack", "Support fat metabolism and NAD+ availability together.",
                  [{"name": "5-Amino-1MQ", "dose": "100 mg daily"},
                   {"name": "NAD+", "dose": "100 mg SC 2x/week"}],
                  ["5-Amino-1MQ each morning.",
                   "NAD+ Mon/Thu (slow injection).",
                   "Hydration and consistent training.",
                   "Assess energy and waist at week 6."],
                  "Metabolic + longevity synergy", "8–12 weeks"),
            proto(4, "Lean Recomposition Stack", "Fat metabolism with mitochondrial support.",
                  [{"name": "5-Amino-1MQ", "dose": "100–150 mg daily"},
                   {"name": "MOTS-c", "dose": "5 mg 2x/week"}],
                  ["Titrate to 150 mg if well tolerated.",
                   "MOTS-c Mon/Thu mornings.",
                   "Resistance training 3–4x/week; steps 8–10k."],
                  "Recomposition phases", "12 weeks"),
        ],
    },
    {
        "slug": "mots-c", "peptide_slug": "mots-c", "peptide_name": "MOTS-c",
        "title": "MOTS-c Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Metabolism / Longevity", "category_slug": "metabolism-longevity",
        "classification": "Mitochondrial-Derived Peptide (16aa)",
        "also_known_as": ["Mitochondrial ORF of the 12S rRNA type-c"],
        "description": "MOTS-c is a mitochondrial-derived peptide researched for metabolic regulation, insulin sensitivity, exercise capacity and cellular stress resistance. It activates AMPK, mimicking many benefits of exercise at the cellular level.",
        "core_info": {
            "function": "AMPK activation, insulin sensitivity, endurance and metabolic health.",
            "typical_dosage": "5–10 mg SC 2–3x/week",
            "administration": "Subcutaneous injection",
            "best_timing": "Morning of training days",
            "common_cycle": "4–8 weeks on, then break",
            "common_pairings": ["NAD+", "Tirzepatide", "5-Amino-1MQ", "HGH"],
        },
        "protocols": [
            proto(1, "Metabolic Priming Protocol", "Baseline AMPK activation and insulin sensitivity.",
                  [{"name": "MOTS-c", "dose": "5 mg SC 2x/week"}],
                  ["Reconstitute 10 mg vial with 2 mL bacteriostatic water (5 mg = 1 mL).",
                   "Inject Monday and Thursday mornings.",
                   "Time on training days for exercise-mimetic effect.",
                   "Run 4–8 weeks, then a 2–4 week break."],
                  "Insulin sensitivity and metabolic health", "4–8 weeks"),
            proto(2, "Endurance & Performance Stack", "Exercise capacity and recovery.",
                  [{"name": "MOTS-c", "dose": "10 mg/week split 2x"},
                   {"name": "NAD+", "dose": "100 mg 2x/week"}],
                  ["MOTS-c 5 mg Mon/Thu.",
                   "NAD+ Tue/Fri (slow injection).",
                   "Schedule around endurance sessions.",
                   "Hydrate and track output weekly."],
                  "Endurance athletes and active researchers", "6–8 weeks"),
            proto(3, "Fat Loss Support Stack", "Metabolic drive during a caloric deficit.",
                  [{"name": "MOTS-c", "dose": "5 mg 2x/week"},
                   {"name": "5-Amino-1MQ", "dose": "100 mg daily"}],
                  ["MOTS-c Mon/Thu; 5-Amino-1MQ each morning.",
                   "Fasted cardio 2–3x/week.",
                   "Protein ≥1.8 g/kg."],
                  "Fat loss with metabolic support", "8 weeks"),
            proto(4, "GLP-1 Metabolic Reset Stack", "Insulin sensitivity support alongside incretin therapy.",
                  [{"name": "MOTS-c", "dose": "5 mg 2x/week"},
                   {"name": "Tirzepatide", "dose": "per ongoing protocol"}],
                  ["Continue weekly Tirzepatide.",
                   "MOTS-c Mon/Thu mornings.",
                   "Resistance training to preserve lean mass."],
                  "Metabolic optimization on GLP-1s", "8–12 weeks"),
        ],
    },
    {
        "slug": "slu-pp-332", "peptide_slug": "slu-pp-332", "peptide_name": "SLU-PP-332",
        "title": "SLU-PP-332 Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Metabolism / Longevity", "category_slug": "metabolism-longevity",
        "classification": "ERR Agonist (Exercise Mimetic)",
        "also_known_as": ["ERRα agonist"],
        "description": "SLU-PP-332 is an ERR (estrogen-related receptor) agonist researched as an 'exercise mimetic' — increasing mitochondrial biogenesis, oxidative metabolism and endurance-type adaptations without additional training load.",
        "core_info": {
            "function": "Mitochondrial biogenesis, oxidative metabolism and endurance adaptations.",
            "typical_dosage": "250 mcg 1–2x daily",
            "administration": "Subcutaneous injection",
            "best_timing": "Pre-activity / morning",
            "common_cycle": "6–8 weeks",
            "common_pairings": ["MOTS-c", "Tirzepatide", "Retatrutide", "HGH Fragment 176-191"],
        },
        "protocols": [
            proto(1, "Exercise Mimetic Protocol", "Baseline oxidative-metabolism support.",
                  [{"name": "SLU-PP-332", "dose": "250 mcg SC 1x daily"}],
                  ["Reconstitute per label; draw 250 mcg.",
                   "Inject SC each morning (or pre-training).",
                   "Combine with 2–3 LISS cardio sessions weekly.",
                   "Run 6–8 weeks."],
                  "Endurance and metabolic conditioning", "6–8 weeks"),
            proto(2, "Fat Oxidation Stack", "Drive fat metabolism during a cut.",
                  [{"name": "SLU-PP-332", "dose": "250 mcg 2x daily (5 days/week)"},
                   {"name": "HGH Fragment 176-191", "dose": "250 mcg pre-cardio"}],
                  ["SLU-PP-332 morning and midday, weekdays.",
                   "Frag 250 mcg before fasted cardio.",
                   "4–5 cardio sessions/week; electrolytes daily."],
                  "Fat oxidation and conditioning", "6–8 weeks"),
            proto(3, "Plateau Breaker Companion", "Add oxidative capacity to a stalled GLP-1 cut.",
                  [{"name": "SLU-PP-332", "dose": "250 mcg 2x daily, 5 days/week"},
                   {"name": "Tirzepatide or Retatrutide", "dose": "per ongoing protocol"}],
                  ["Continue the weekly GLP-1.",
                   "Add SLU-PP-332 morning and midday, weekdays only.",
                   "Add 2 fasted LISS sessions.",
                   "Reassess after 4 weeks."],
                  "Breaking weight-loss plateaus", "4–8 weeks"),
            proto(4, "Endurance Base Stack", "Mitochondrial density for aerobic base building.",
                  [{"name": "SLU-PP-332", "dose": "250 mcg daily"},
                   {"name": "MOTS-c", "dose": "5 mg 2x/week"}],
                  ["SLU-PP-332 pre-training.",
                   "MOTS-c Mon/Thu.",
                   "Zone-2 cardio 3–4x/week."],
                  "Aerobic base and endurance", "8 weeks"),
        ],
    },
    {
        "slug": "epithalon", "peptide_slug": "epithalon", "peptide_name": "Epithalon",
        "title": "Epithalon Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Bioregulators / Longevity", "category_slug": "bioregulators-longevity",
        "classification": "Telomerase-Activating Tetrapeptide (Ala-Glu-Asp-Gly)",
        "also_known_as": ["Epitalon", "AEDG"],
        "description": "Epithalon is a synthetic tetrapeptide researched for telomerase activation, circadian/pineal regulation (melatonin) and longevity signaling. Typically run in short intensive blocks 1–2x per year.",
        "core_info": {
            "function": "Telomerase support, circadian/pineal regulation, longevity signaling.",
            "typical_dosage": "5–10 mg SC daily for 10–20 days",
            "administration": "Subcutaneous injection",
            "best_timing": "Evening (supports melatonin rhythm)",
            "common_cycle": "10–20 day blocks, 1–2x per year",
            "common_pairings": ["Glutathione", "NAD+", "GHK-Cu", "Glow Blend"],
        },
        "protocols": [
            proto(1, "Classic 20-Day Block Protocol", "Traditional longevity block dosing.",
                  [{"name": "Epithalon", "dose": "5–10 mg SC daily for 20 days"}],
                  ["Reconstitute 10 mg vial with 2 mL bacteriostatic water.",
                   "Inject 5–10 mg SC each evening for 20 consecutive days.",
                   "Support sleep hygiene during the block.",
                   "Repeat block once or twice per year."],
                  "Periodic longevity blocks", "20 days"),
            proto(2, "Sleep & Circadian Reset", "Restore healthy sleep-wake rhythm.",
                  [{"name": "Epithalon", "dose": "5 mg SC nightly for 10 days"}],
                  ["Inject 5 mg SC 1–2h before bed for 10 nights.",
                   "Fixed sleep/wake times; dim light in the evening.",
                   "Assess sleep quality at day 10.",
                   "Repeat quarterly if beneficial."],
                  "Circadian and sleep support", "10 days"),
            proto(3, "Longevity Synergy Stack", "Combine telomere and antioxidant support.",
                  [{"name": "Epithalon", "dose": "10 mg daily for 20 days"},
                   {"name": "Glutathione", "dose": "200 mg 2x/week"},
                   {"name": "NAD+", "dose": "100 mg 2x/week"}],
                  ["Epithalon nightly for 20 days.",
                   "Glutathione and NAD+ twice weekly through the block.",
                   "Prioritize sleep, hydration and whole-food nutrition."],
                  "Comprehensive longevity blocks", "20 days"),
            proto(4, "Skin & Regeneration Stack", "Longevity block with skin-quality focus.",
                  [{"name": "Epithalon", "dose": "5 mg nightly for 20 days"},
                   {"name": "Glow Blend", "dose": "1–2 mg GHK-Cu equivalent nightly"}],
                  ["Epithalon each evening.",
                   "Glow Blend nightly per its standard dosing.",
                   "SPF daily; photograph skin every 10 days."],
                  "Anti-aging with skin focus", "20 days"),
        ],
    },
    {
        "slug": "foxo4", "peptide_slug": "foxo4", "peptide_name": "FOXO4",
        "title": "FOXO4 Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Bioregulators / Longevity", "category_slug": "bioregulators-longevity",
        "classification": "FOXO4-DRI Senolytic Peptide",
        "also_known_as": ["FOXO4-DRI", "Proxofim"],
        "description": "FOXO4-DRI is a senolytic peptide researched for selectively clearing senescent ('zombie') cells by disrupting the FOXO4–p53 interaction. Run in short pulsed cycles as part of longevity research protocols.",
        "core_info": {
            "function": "Senolytic — targets senescent cell clearance via FOXO4/p53 disruption.",
            "typical_dosage": "Pulsed: dose every other day within a short block",
            "administration": "Subcutaneous or IV (research)",
            "best_timing": "Per pulsed schedule",
            "common_cycle": "Short pulsed blocks, spaced months apart",
            "common_pairings": ["Epithalon", "NAD+", "Glutathione"],
        },
        "protocols": [
            proto(1, "Pulsed Senolytic Block", "Traditional 'hit-and-run' senolytic pulsing.",
                  [{"name": "FOXO4", "dose": "reconstituted; dose every other day for 3 doses"}],
                  ["Reconstitute per label with bacteriostatic water.",
                   "Dose on days 1, 3 and 5 (every other day).",
                   "Support hydration and recovery around the block.",
                   "Space blocks several months apart."],
                  "Periodic senolytic research", "1 week block"),
            proto(2, "Longevity Foundation Stack", "Pair senolytic pulsing with repair support.",
                  [{"name": "FOXO4", "dose": "every other day x3"},
                   {"name": "NAD+", "dose": "100 mg 2x/week"}],
                  ["Run the FOXO4 pulse (days 1/3/5).",
                   "NAD+ twice weekly during and after the block.",
                   "Prioritize sleep and anti-inflammatory nutrition."],
                  "Senescence + cellular repair", "2–3 weeks"),
            proto(3, "Comprehensive Anti-Senescence Stack", "Layer senolytic, telomere and antioxidant support.",
                  [{"name": "FOXO4", "dose": "every other day x3"},
                   {"name": "Epithalon", "dose": "5 mg nightly x20 days"},
                   {"name": "Glutathione", "dose": "200 mg 2x/week"}],
                  ["Start with the FOXO4 pulse block.",
                   "Follow with a 20-day Epithalon block.",
                   "Glutathione throughout for antioxidant support."],
                  "Advanced longevity researchers", "4 weeks"),
        ],
    },
    # ───────────────────────── SKIN / REGENERATION ─────────────────────────
    {
        "slug": "kpv", "peptide_slug": "kpv", "peptide_name": "KPV",
        "title": "KPV Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Skin / Regeneration", "category_slug": "skin-regeneration",
        "classification": "Anti-Inflammatory Tripeptide (α-MSH 11-13)",
        "also_known_as": ["Lys-Pro-Val"],
        "description": "KPV is the C-terminal tripeptide of α-MSH, researched for its anti-inflammatory and gut-healing properties without pigmentation effects. Studied for inflammatory skin conditions, gut integrity and wound healing.",
        "core_info": {
            "function": "Anti-inflammatory signaling, skin/gut healing, immune modulation.",
            "typical_dosage": "250–500 mcg SC daily (or oral for gut focus)",
            "administration": "Subcutaneous injection or oral capsule",
            "best_timing": "Morning or evening, consistent daily",
            "common_cycle": "4–8 weeks",
            "common_pairings": ["BPC-157", "GHK-Cu", "Glow Blend", "KPV"],
        },
        "protocols": [
            proto(1, "Anti-Inflammatory Protocol", "Baseline systemic anti-inflammatory support.",
                  [{"name": "KPV", "dose": "250–500 mcg SC daily"}],
                  ["Reconstitute 10 mg vial with 2 mL bacteriostatic water (500 mcg = 0.1 mL).",
                   "Inject 250–500 mcg SC once daily, consistent time.",
                   "Run 4–8 weeks; assess inflammatory markers/skin at week 4.",
                   "Store reconstituted vial at 2–8°C."],
                  "Inflammatory skin and general inflammation", "4–8 weeks"),
            proto(2, "Gut Healing Protocol", "Oral dosing for intestinal integrity.",
                  [{"name": "KPV", "dose": "500 mcg oral daily"},
                   {"name": "BPC-157", "dose": "250 mcg oral daily"}],
                  ["Take KPV and BPC-157 orally on an empty stomach each morning.",
                   "Avoid food 20–30 min after dosing.",
                   "Run 4–6 weeks; support with an anti-inflammatory diet."],
                  "Gut integrity research", "4–6 weeks"),
            proto(3, "Skin Calming Stack", "Combine anti-inflammatory with regeneration.",
                  [{"name": "KPV", "dose": "250 mcg SC daily"},
                   {"name": "GHK-Cu", "dose": "1–2 mg SC nightly"}],
                  ["KPV each morning; GHK-Cu each evening.",
                   "Use into or near areas of concern (SC).",
                   "SPF daily; gentle skincare (no strong acids)."],
                  "Reactive or inflamed skin", "6 weeks"),
            proto(4, "Post-Procedure Anti-Inflammatory", "Control inflammation after aesthetic procedures.",
                  [{"name": "KPV", "dose": "500 mcg SC daily for 10 days"}],
                  ["Start 24–48h after the procedure.",
                   "Inject 500 mcg SC daily for 10 days.",
                   "Avoid retinoids/acids during the window; keep skin hydrated."],
                  "Recovery after microneedling/laser/peels", "10–14 days"),
        ],
    },
    {
        "slug": "ahk-cu", "peptide_slug": "ahk-cu", "peptide_name": "AHK-Cu",
        "title": "AHK-Cu Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Skin / Regeneration", "category_slug": "skin-regeneration",
        "classification": "Copper Tripeptide (Ala-His-Lys-Cu)",
        "also_known_as": ["AHK Copper Peptide"],
        "description": "AHK-Cu is a copper-binding tripeptide researched primarily for hair follicle stimulation, dermal papilla cell proliferation and vascularization. Often paired with GHK-Cu for combined skin-and-hair protocols.",
        "core_info": {
            "function": "Hair follicle stimulation, angiogenesis and dermal support.",
            "typical_dosage": "1–2 mg into scalp-adjacent sites 3x/week",
            "administration": "Subcutaneous (scalp-adjacent) or topical",
            "best_timing": "Evening, on clean skin/scalp",
            "common_cycle": "8–12 weeks",
            "common_pairings": ["GHK-Cu", "PTD-DBM", "Glow Blend", "KPV"],
        },
        "protocols": [
            proto(1, "Hair Density Protocol", "Baseline follicle stimulation.",
                  [{"name": "AHK-Cu", "dose": "1 mg SC scalp-adjacent 3x/week"}],
                  ["Reconstitute per label; draw 1 mg.",
                   "Inject SC into scalp-adjacent sites Mon/Wed/Fri.",
                   "Optional 0.5 mm dermaroller weekly (not same day).",
                   "Photograph density every 2 weeks."],
                  "Early hair-density research", "8–12 weeks"),
            proto(2, "Hair Synergy Stack", "Combine two hair-active peptides.",
                  [{"name": "AHK-Cu", "dose": "1 mg 3x/week"},
                   {"name": "PTD-DBM", "dose": "topical/SC per protocol"}],
                  ["AHK-Cu Mon/Wed/Fri.",
                   "PTD-DBM on alternate days per its protocol.",
                   "Consistent scalp care; avoid harsh products.",
                   "Assess at week 8."],
                  "Comprehensive hair protocols", "12 weeks"),
            proto(3, "Skin & Hair Stack", "Whole aesthetic approach with GHK-Cu.",
                  [{"name": "AHK-Cu", "dose": "1 mg 3x/week (scalp)"},
                   {"name": "GHK-Cu", "dose": "1–2 mg nightly (skin)"}],
                  ["AHK-Cu into scalp sites Mon/Wed/Fri.",
                   "GHK-Cu nightly for skin quality.",
                   "SPF daily; photograph progress bi-weekly."],
                  "Combined skin + hair goals", "8–12 weeks"),
            proto(4, "Glow Blend Hair Add-On", "Layer AHK-Cu onto a Glow Blend cycle.",
                  [{"name": "AHK-Cu", "dose": "1 mg 3x/week"},
                   {"name": "Glow Blend", "dose": "1–2 mg GHK-Cu equivalent nightly"}],
                  ["Run Glow Blend nightly per its protocol.",
                   "Add AHK-Cu into scalp sites Mon/Wed/Fri.",
                   "Track skin and hair separately every 2 weeks."],
                  "Glow Blend users adding hair focus", "8–12 weeks"),
        ],
    },
    {
        "slug": "ghk-basic", "peptide_slug": "ghk-basic", "peptide_name": "GHK Basic",
        "title": "GHK Basic Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Skin / Regeneration", "category_slug": "skin-regeneration",
        "classification": "GHK Tripeptide (copper-free base, Gly-His-Lys)",
        "also_known_as": ["GHK", "Glycyl-Histidyl-Lysine"],
        "description": "GHK Basic is the copper-free glycyl-histidyl-lysine tripeptide researched for collagen synthesis, tissue remodeling and gene-expression 'resetting' toward a younger profile. A gentler entry point than copper-bound GHK-Cu.",
        "core_info": {
            "function": "Collagen synthesis, tissue remodeling and skin regeneration.",
            "typical_dosage": "1–2 mg SC daily",
            "administration": "Subcutaneous injection",
            "best_timing": "Evening",
            "common_cycle": "6–8 weeks on, 4 weeks off",
            "common_pairings": ["GHK-Cu", "Glow Blend", "Glutathione", "Epithalon"],
        },
        "protocols": [
            proto(1, "Collagen Induction Protocol", "Baseline skin-remodeling dosing.",
                  [{"name": "GHK Basic", "dose": "1 mg SC nightly"}],
                  ["Reconstitute 50 mg vial per label.",
                   "Inject 1 mg SC each evening.",
                   "Run 6 weeks, then 4 weeks off.",
                   "SPF daily; consistent gentle skincare."],
                  "First-time GHK skin research", "6 weeks"),
            proto(2, "Advanced Rejuvenation Stack", "Layer copper-free and copper-bound GHK.",
                  [{"name": "GHK Basic", "dose": "1 mg nightly"},
                   {"name": "GHK-Cu", "dose": "1 mg alternate nights"}],
                  ["Alternate GHK Basic and GHK-Cu on consecutive nights.",
                   "Track skin firmness and tone every 2 weeks.",
                   "SPF 50 daily."],
                  "Experienced users seeking stronger remodeling", "8 weeks"),
            proto(3, "Skin Quality + Antioxidant Stack", "Regeneration plus brightening support.",
                  [{"name": "GHK Basic", "dose": "1–2 mg nightly"},
                   {"name": "Glutathione", "dose": "200 mg 2x/week"}],
                  ["GHK Basic nightly.",
                   "Glutathione Tue/Fri mornings.",
                   "Hydration and SPF; photograph progress."],
                  "Tone, texture and luminosity", "8 weeks"),
            proto(4, "Longevity Skin Block", "Combine with a telomere block for anti-aging.",
                  [{"name": "GHK Basic", "dose": "1 mg nightly"},
                   {"name": "Epithalon", "dose": "5 mg nightly x20 days"}],
                  ["GHK Basic nightly throughout.",
                   "Run a concurrent 20-day Epithalon block.",
                   "Prioritize sleep and hydration."],
                  "Anti-aging skin blocks", "20 days"),
        ],
    },
    {
        "slug": "klow-blend", "peptide_slug": "klow-blend", "peptide_name": "Klow Blend",
        "title": "Klow Blend Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Skin / Regeneration", "category_slug": "skin-regeneration",
        "classification": "GHK-Cu + KPV + BPC-157 + TB-500 Combination (80mg)",
        "also_known_as": ["Klow 80", "K-Glow"],
        "description": "Klow Blend is a 4-in-1 formula combining GHK-Cu (collagen), KPV (anti-inflammatory), BPC-157 and TB-500 (repair/regeneration). Researched for advanced skin rejuvenation with strong anti-inflammatory and whole-body recovery components.",
        "core_info": {
            "function": "Skin rejuvenation, anti-inflammatory action, tissue repair and recovery.",
            "typical_dosage": "Dosed by GHK-Cu content: 1–2 mg daily",
            "administration": "Subcutaneous injection",
            "best_timing": "Evening, before bed",
            "common_cycle": "6–8 weeks on, 4 weeks off",
            "common_pairings": ["Glow Blend", "Glutathione", "Epithalon", "AHK-Cu"],
        },
        "protocols": [
            proto(1, "Beginner Klow Protocol", "Introduction to the 4-in-1 blend.",
                  [{"name": "Klow Blend", "dose": "1 mg GHK-Cu equivalent nightly"}],
                  ["Reconstitute 80 mg vial with 2 mL bacteriostatic water.",
                   "Inject the equivalent of 1 mg GHK-Cu SC nightly.",
                   "Rotate injection sites; avoid the same spot within 48h.",
                   "Run 6 weeks, then 4 weeks off."],
                  "First-time users of multi-peptide skin blends", "6 weeks"),
            proto(2, "Total Rejuvenation Stack", "Maximum skin quality plus anti-inflammatory action.",
                  [{"name": "Klow Blend", "dose": "2 mg GHK-Cu equivalent nightly"},
                   {"name": "Glutathione", "dose": "200 mg 2x/week"}],
                  ["Klow Blend nightly at the higher dose.",
                   "Glutathione Mon/Thu mornings.",
                   "SPF 50 daily — copper peptides raise skin turnover."],
                  "Advanced anti-aging and luminosity", "8 weeks"),
            proto(3, "Recovery & Skin Stack", "Leverage the BPC/TB content for connective tissue.",
                  [{"name": "Klow Blend", "dose": "2 mg GHK-Cu equivalent daily"},
                   {"name": "BPC-157", "dose": "250 mcg SC near affected area"}],
                  ["Klow Blend nightly (systemic).",
                   "Additional BPC-157 near the target tissue.",
                   "Light mobility work; avoid maximal loading for 3 weeks."],
                  "Skin goals with joint/tendon complaints", "6–8 weeks"),
            proto(4, "Post-Procedure Recovery", "Accelerated healing after aesthetic procedures.",
                  [{"name": "Klow Blend", "dose": "2 mg GHK-Cu equivalent daily for 14 days"}],
                  ["Start 48h after the procedure (never on broken-skin day).",
                   "Inject nightly for 14 days.",
                   "Avoid retinoids/acids during the window; keep skin hydrated."],
                  "Recovery windows after procedures", "2–3 weeks per procedure"),
        ],
    },
    {
        "slug": "glutathione", "peptide_slug": "glutathione", "peptide_name": "Glutathione",
        "title": "Glutathione Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Skin / Regeneration", "category_slug": "skin-regeneration",
        "classification": "Master Antioxidant Tripeptide (GSH)",
        "also_known_as": ["GSH", "Reduced Glutathione"],
        "description": "Glutathione is the body's master antioxidant, researched for detoxification, skin brightening, immune support and cellular protection against oxidative stress. Injectable delivery bypasses poor oral absorption.",
        "core_info": {
            "function": "Antioxidant defense, detoxification, skin brightening, immune support.",
            "typical_dosage": "200–600 mg SC/IM 2–3x/week",
            "administration": "Subcutaneous or intramuscular injection",
            "best_timing": "Morning",
            "common_cycle": "8–12 weeks or continuous",
            "common_pairings": ["Vitamin C", "NAD+", "GHK-Cu", "Glow Blend"],
        },
        "protocols": [
            proto(1, "Antioxidant Foundation Protocol", "Baseline oxidative-stress support.",
                  [{"name": "Glutathione", "dose": "200 mg SC 2x/week"}],
                  ["Reconstitute 1500 mg vial per label.",
                   "Inject 200 mg SC Monday and Thursday mornings.",
                   "Store reconstituted vial refrigerated, protected from light.",
                   "Assess energy and skin tone at week 4."],
                  "General antioxidant/detox support", "8–12 weeks"),
            proto(2, "Skin Brightening Stack", "Even tone and luminosity.",
                  [{"name": "Glutathione", "dose": "600 mg 2x/week"},
                   {"name": "Vitamin C", "dose": "co-administered where available"}],
                  ["Glutathione 600 mg Mon/Thu.",
                   "Pair with vitamin C to support recycling of GSH.",
                   "SPF 50 daily is essential for brightening results.",
                   "Photograph tone every 2 weeks."],
                  "Skin tone and brightening research", "10–12 weeks"),
            proto(3, "Detox & Recovery Stack", "Cellular protection during intense phases.",
                  [{"name": "Glutathione", "dose": "400 mg 2x/week"},
                   {"name": "NAD+", "dose": "100 mg 2x/week"}],
                  ["Glutathione Mon/Thu; NAD+ Tue/Fri.",
                   "Hydration ≥3L; limit alcohol.",
                   "Assess recovery and energy at week 4."],
                  "Detox and recovery focus", "8 weeks"),
            proto(4, "Skin Rejuvenation Add-On", "Brightening layered on a collagen protocol.",
                  [{"name": "Glutathione", "dose": "400 mg 2x/week"},
                   {"name": "Glow Blend", "dose": "1–2 mg GHK-Cu equivalent nightly"}],
                  ["Run Glow Blend nightly per its protocol.",
                   "Add Glutathione Mon/Thu mornings.",
                   "SPF daily; track tone and firmness separately."],
                  "Combined brightening + collagen", "8 weeks"),
        ],
    },
    {
        "slug": "ptd-dbm", "peptide_slug": "ptd-dbm", "peptide_name": "PTD-DBM",
        "title": "PTD-DBM Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Skin / Regeneration", "category_slug": "skin-regeneration",
        "classification": "Wnt/β-catenin Pathway Peptide (Hair)",
        "also_known_as": ["PTD-DBM peptide"],
        "description": "PTD-DBM is a peptide researched for hair regeneration via the Wnt/β-catenin pathway — inhibiting CXXC5 to reactivate follicle stem cells. Typically applied topically, often combined with valproic acid or microneedling in hair research.",
        "core_info": {
            "function": "Reactivates hair follicle stem cells via Wnt/β-catenin signaling.",
            "typical_dosage": "Topical application to scalp daily",
            "administration": "Topical (scalp), often with microneedling",
            "best_timing": "Evening on clean, dry scalp",
            "common_cycle": "12–16 weeks (hair cycles are slow)",
            "common_pairings": ["AHK-Cu", "GHK-Cu", "Valproic acid (research)"],
        },
        "protocols": [
            proto(1, "Topical Hair Protocol", "Baseline scalp application.",
                  [{"name": "PTD-DBM", "dose": "apply to affected scalp areas daily"}],
                  ["Reconstitute/prepare per label into a topical solution.",
                   "Apply to clean, dry scalp each evening; massage in.",
                   "Leave on overnight; avoid rinsing for several hours.",
                   "Hair cycles are slow — commit to 12–16 weeks."],
                  "Early hair-regeneration research", "12–16 weeks"),
            proto(2, "Microneedling Synergy Protocol", "Enhance delivery with weekly microneedling.",
                  [{"name": "PTD-DBM", "dose": "topical daily"}],
                  ["Microneedle scalp 0.5–1.0 mm once weekly.",
                   "Apply PTD-DBM on non-needling days (not immediately after).",
                   "Keep the scalp clean; avoid harsh products.",
                   "Photograph density every 2 weeks."],
                  "Maximizing topical uptake", "12–16 weeks"),
            proto(3, "Dual Copper-Peptide Hair Stack", "Combine Wnt activation with follicle stimulation.",
                  [{"name": "PTD-DBM", "dose": "topical daily"},
                   {"name": "AHK-Cu", "dose": "1 mg SC scalp-adjacent 3x/week"}],
                  ["PTD-DBM topical nightly.",
                   "AHK-Cu into scalp sites Mon/Wed/Fri.",
                   "Weekly microneedling on a separate day.",
                   "Assess at week 12."],
                  "Comprehensive hair protocols", "12–16 weeks"),
        ],
    },
    # ───────────────────────── HORMONAL / OTHER ─────────────────────────
    {
        "slug": "kisspeptin", "peptide_slug": "kisspeptin", "peptide_name": "Kisspeptin",
        "title": "Kisspeptin Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Hormonal / Sexual Health", "category_slug": "hormonal-sexual-health",
        "classification": "GnRH-Stimulating Neuropeptide (Kisspeptin-10)",
        "also_known_as": ["Kisspeptin-10", "KP-10", "Metastin"],
        "description": "Kisspeptin is an upstream regulator of the reproductive axis, stimulating GnRH release and downstream LH/FSH. Researched for hormonal support, libido and fertility signaling with a more physiological pattern than direct hormone administration.",
        "core_info": {
            "function": "Stimulates the GnRH → LH/FSH axis for hormonal and reproductive support.",
            "typical_dosage": "Research dosing varies; low mcg-range SC",
            "administration": "Subcutaneous injection",
            "best_timing": "Consistent time; pre-activity for libido research",
            "common_cycle": "4–8 weeks",
            "common_pairings": ["PT-141", "Oxytocin"],
        },
        "protocols": [
            proto(1, "HPG Axis Support Protocol", "Baseline stimulation of the reproductive axis.",
                  [{"name": "Kisspeptin", "dose": "low mcg-range SC, per label, 2–3x/week"}],
                  ["Reconstitute 10 mg vial per label.",
                   "Inject the labeled research dose SC 2–3x/week.",
                   "Keep timing consistent; log any subjective changes.",
                   "Run 4–8 weeks, then reassess."],
                  "Hormonal-axis research", "4–8 weeks"),
            proto(2, "Libido Support Stack", "Combine central pathways for libido research.",
                  [{"name": "Kisspeptin", "dose": "per label, pre-activity"},
                   {"name": "PT-141", "dose": "per PT-141 protocol"}],
                  ["Kisspeptin on schedule.",
                   "PT-141 dosed 45–60 min before activity per its protocol.",
                   "Do not stack novel compounds on the same first trial day."],
                  "Libido and sexual-health research", "4–6 weeks"),
            proto(3, "Wellbeing & Connection Stack", "Layer with oxytocin for mood/connection research.",
                  [{"name": "Kisspeptin", "dose": "per label 2x/week"},
                   {"name": "Oxytocin", "dose": "per oxytocin protocol"}],
                  ["Kisspeptin twice weekly.",
                   "Oxytocin per its protocol.",
                   "Track mood and subjective wellbeing weekly."],
                  "Mood, connection and hormonal wellbeing", "4–6 weeks"),
        ],
    },
    {
        "slug": "oxytocin", "peptide_slug": "oxytocin", "peptide_name": "Oxytocin",
        "title": "Oxytocin Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Hormonal / Sexual Health", "category_slug": "hormonal-sexual-health",
        "classification": "Neuropeptide Hormone (9aa)",
        "also_known_as": ["OXT", "Bonding Hormone"],
        "description": "Oxytocin is a neuropeptide researched for social bonding, mood, stress reduction and sexual wellbeing. Delivered subcutaneously or intranasally in research settings, with effects on trust, calm and connection.",
        "core_info": {
            "function": "Social bonding, mood elevation, stress reduction, sexual wellbeing.",
            "typical_dosage": "Low IU/mcg range, intranasal or SC",
            "administration": "Intranasal or subcutaneous",
            "best_timing": "Before social/intimate settings or to reduce acute stress",
            "common_cycle": "As-needed or short blocks",
            "common_pairings": ["PT-141", "Kisspeptin"],
        },
        "protocols": [
            proto(1, "Mood & Connection Protocol", "Baseline social/mood support.",
                  [{"name": "Oxytocin", "dose": "low-range dose, intranasal or SC, as needed"}],
                  ["Prepare per label (intranasal solution or SC).",
                   "Use 30–45 min before the intended social setting.",
                   "Start low; assess subjective calm and connection.",
                   "Avoid daily heavy use — periodic works best."],
                  "Mood, stress and social wellbeing", "As-needed / short blocks"),
            proto(2, "Intimacy Stack", "Combine bonding and libido pathways.",
                  [{"name": "Oxytocin", "dose": "pre-activity, low range"},
                   {"name": "PT-141", "dose": "per PT-141 protocol"}],
                  ["PT-141 45–60 min before activity per its protocol.",
                   "Oxytocin 30 min before for connection/calm.",
                   "Trial each separately before combining."],
                  "Intimacy and sexual-wellbeing research", "As-needed"),
            proto(3, "Stress Reset Protocol", "Acute stress and mood support block.",
                  [{"name": "Oxytocin", "dose": "low range, evenings for 2 weeks"}],
                  ["Use in the evening to wind down for a 2-week block.",
                   "Pair with breathing/relaxation practice.",
                   "Assess sleep and stress at day 14."],
                  "Acute stress-reduction research", "2 weeks"),
        ],
    },
    {
        "slug": "cartalax", "peptide_slug": "cartalax", "peptide_name": "Cartalax",
        "title": "Cartalax Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Bioregulators / Longevity", "category_slug": "bioregulators-longevity",
        "classification": "Cartilage Bioregulator Peptide (Ala-Glu-Asp)",
        "also_known_as": ["AED", "Cartalax bioregulator"],
        "description": "Cartalax is a short peptide bioregulator (Khavinson class) researched for cartilage, connective tissue and vascular support. Run in short intensive blocks characteristic of peptide bioregulator protocols.",
        "core_info": {
            "function": "Cartilage/connective-tissue support and vascular regulation.",
            "typical_dosage": "5–10 mg SC daily for 10–20 days",
            "administration": "Subcutaneous injection",
            "best_timing": "Consistent daily time",
            "common_cycle": "10–20 day blocks, 1–2x per year",
            "common_pairings": ["Epithalon", "BPC-157", "TB-500", "GHK-Cu"],
        },
        "protocols": [
            proto(1, "Connective Tissue Block", "Traditional bioregulator block for joints.",
                  [{"name": "Cartalax", "dose": "5–10 mg SC daily for 20 days"}],
                  ["Reconstitute 20 mg vial per label.",
                   "Inject 5–10 mg SC daily for 20 consecutive days.",
                   "Light mobility work; avoid maximal joint loading.",
                   "Repeat block 1–2x per year."],
                  "Cartilage and connective-tissue research", "20 days"),
            proto(2, "Joint Recovery Stack", "Add repair peptides to the block.",
                  [{"name": "Cartalax", "dose": "10 mg daily x20 days"},
                   {"name": "BPC-157", "dose": "250 mcg SC daily near joint"}],
                  ["Cartalax daily for the 20-day block.",
                   "BPC-157 near the affected joint daily.",
                   "Progressive, controlled loading only.",
                   "Reassess function at day 20."],
                  "Active joint/tendon recovery", "20 days"),
            proto(3, "Regeneration Stack", "Combine with TB-500 for systemic recovery.",
                  [{"name": "Cartalax", "dose": "10 mg daily x20 days"},
                   {"name": "TB-500", "dose": "2–2.5 mg SC 2x/week"}],
                  ["Cartalax daily; TB-500 twice weekly.",
                   "Prioritize sleep and protein for tissue repair.",
                   "Avoid high-impact activity during the block."],
                  "Comprehensive connective-tissue recovery", "3 weeks"),
        ],
    },
    {
        "slug": "ace-031", "peptide_slug": "ace-031", "peptide_name": "ACE-031",
        "title": "ACE-031 Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Muscle / Performance", "category_slug": "muscle-performance",
        "classification": "Myostatin/Activin Decoy Receptor (ActRIIB-Fc)",
        "also_known_as": ["ActRIIB-Fc", "Ramatercept"],
        "description": "ACE-031 is a soluble activin receptor (ActRIIB-Fc) researched for muscle growth by binding and neutralizing myostatin and related ligands. This removes a key brake on muscle mass, studied for hypertrophy and muscle-wasting contexts.",
        "core_info": {
            "function": "Neutralizes myostatin/activin to support muscle mass and strength.",
            "typical_dosage": "Low mg-range, dosed roughly every 2–4 weeks (long-acting)",
            "administration": "Subcutaneous injection",
            "best_timing": "Fixed schedule (long half-life)",
            "common_cycle": "8–12 weeks",
            "common_pairings": ["HGH", "IGF-1 LR3", "CJC-1295 + Ipamorelin"],
        },
        "protocols": [
            proto(1, "Myostatin Inhibition Protocol", "Baseline muscle-support dosing.",
                  [{"name": "ACE-031", "dose": "per label, SC every 2–4 weeks"}],
                  ["Reconstitute 1 mg vial per label.",
                   "Inject SC on a fixed schedule (long-acting — infrequent dosing).",
                   "Train with progressive overload 3–4x/week.",
                   "Protein ≥2 g/kg; monitor for peripheral effects."],
                  "Muscle-mass research", "8–12 weeks"),
            proto(2, "Hypertrophy Stack", "Combine with GH-axis support for growth.",
                  [{"name": "ACE-031", "dose": "per label schedule"},
                   {"name": "HGH", "dose": "2 IU daily"}],
                  ["ACE-031 on its schedule.",
                   "HGH 2 IU AM, 5 days on / 2 off.",
                   "Heavy compound training; ample recovery.",
                   "Reassess strength and size every 4 weeks."],
                  "Advanced hypertrophy research", "12 weeks"),
            proto(3, "Strength & Recovery Stack", "Muscle support with local repair.",
                  [{"name": "ACE-031", "dose": "per label"},
                   {"name": "IGF-1 LR3", "dose": "per IGF-1 LR3 protocol"}],
                  ["ACE-031 on schedule.",
                   "IGF-1 LR3 per its protocol post-training.",
                   "Prioritize sleep and protein.",
                   "Deload every 6th week."],
                  "Strength and lean-mass focus", "8–12 weeks"),
        ],
    },
    {
        "slug": "adamax", "peptide_slug": "adamax", "peptide_name": "Adamax",
        "title": "Adamax Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Nootropic / Cognitive", "category_slug": "nootropic-cognitive",
        "classification": "Semax-Class Nootropic Peptide (N-adamantyl analog)",
        "also_known_as": ["N-adamantyl nootropic peptide"],
        "description": "Adamax is a Semax-class nootropic peptide researched for enhanced focus, memory, neuroprotection and BDNF support — reported to be more potent and longer-acting than Semax. Delivered intranasally in cognitive research.",
        "core_info": {
            "function": "Focus, memory, neuroprotection and BDNF/neurotrophic support.",
            "typical_dosage": "Low mcg-range intranasal, once daily",
            "administration": "Intranasal",
            "best_timing": "Morning (can be stimulating)",
            "common_cycle": "4–6 weeks on, 2 weeks off",
            "common_pairings": ["Semax", "Selank", "NAD+"],
        },
        "protocols": [
            proto(1, "Cognitive Focus Protocol", "Baseline daily nootropic dosing.",
                  [{"name": "Adamax", "dose": "low mcg-range intranasal, 1x daily"}],
                  ["Prepare intranasal solution per label.",
                   "Administer each morning on workdays.",
                   "Assess focus, memory and mood at week 2.",
                   "Run 4–6 weeks, then a 2-week break."],
                  "Focus and memory research", "4–6 weeks"),
            proto(2, "Focus + Calm Stack", "Balance stimulation with anxiolytic support.",
                  [{"name": "Adamax", "dose": "AM intranasal"},
                   {"name": "Selank", "dose": "300 mcg intranasal as needed"}],
                  ["Adamax each morning for drive/focus.",
                   "Selank later in the day for calm without sedation.",
                   "Do not exceed labeled research doses."],
                  "Focus with anxiety balance", "4–6 weeks"),
            proto(3, "Neuroprotection & Energy Stack", "Cognitive support with cellular energy.",
                  [{"name": "Adamax", "dose": "AM intranasal"},
                   {"name": "NAD+", "dose": "100 mg SC 2x/week"}],
                  ["Adamax each morning.",
                   "NAD+ Mon/Thu (slow injection).",
                   "Prioritize sleep; reassess at week 4."],
                  "Neuroprotection and mental energy", "4–6 weeks"),
        ],
    },
]


async def main():
    db = AsyncIOMotorClient(os.environ["MONGO_URL"])[os.environ["DB_NAME"]]
    for hub in HUBS:
        existing = await db.stack_hubs.find_one({"slug": hub["slug"]}, {"_id": 1})
        await db.stack_hubs.replace_one({"slug": hub["slug"]}, hub, upsert=True)
        print(f"{'updated' if existing else 'created'}: {hub['slug']} ({len(hub['protocols'])} protocols)")
    total = await db.stack_hubs.count_documents({})
    print("total hubs:", total)


asyncio.run(main())
