"""Seed 4 new Stack Hubs: Tirzepatide, Retatrutide, Glow Blend, Vitamin B12. Idempotent upsert by slug."""
import asyncio
import os
import uuid
from pathlib import Path

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv(Path(__file__).resolve().parent.parent / ".env")


def proto(order, name, goal, compounds, steps, best_for, duration):
    return {"id": str(uuid.uuid4()), "order": order, "name": name, "goal": goal,
            "compounds": compounds, "protocol": steps, "best_for": best_for, "duration": duration}


HUBS = [
    {
        "slug": "tirzepatide", "peptide_slug": "tirzepatide", "peptide_name": "Tirzepatide",
        "title": "Tirzepatide Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "GLP-1 / Metabolic", "category_slug": "glp1-metabolic",
        "classification": "Dual GIP/GLP-1 Receptor Agonist",
        "also_known_as": ["Mounjaro", "Zepbound", "LY3298176"],
        "description": "Tirzepatide is a dual GIP/GLP-1 receptor agonist and the most researched incretin peptide for weight management and glycemic control. Clinical trials (SURMOUNT, SURPASS) demonstrated up to 22.5% body weight reduction, superior to single GLP-1 agonists.",
        "core_info": {
            "function": "Appetite control, weight reduction, insulin sensitivity and glycemic regulation.",
            "typical_dosage": "2.5–15 mg subcutaneously once weekly (titrated)",
            "administration": "Subcutaneous injection or pre-filled pen (click dosing)",
            "best_timing": "Same day each week, any time, with or without food",
            "common_cycle": "12–24+ weeks with gradual titration",
            "common_pairings": ["Retatrutide", "5-Amino-1MQ", "MOTS-c", "NAD+"],
        },
        "protocols": [
            proto(1, "Standard Titration Protocol", "Progressive weight reduction with minimal GI side effects.",
                  [{"name": "Tirzepatide", "dose": "2.5 mg weekly (weeks 1–4), then 5 mg (weeks 5–8), increase by 2.5 mg every 4 weeks as tolerated"}],
                  ["Reconstitute vial with 1 mL bacteriostatic water (10mg vial = 100 units syringe).",
                   "Weeks 1–4: inject 2.5 mg SC once weekly (25 units of a 10mg/1mL solution).",
                   "Weeks 5–8: increase to 5 mg weekly (50 units).",
                   "Titrate up by 2.5 mg every 4 weeks only if appetite control fades.",
                   "Maintain protein intake ≥1.6 g/kg and hydration ≥3L daily."],
                  "Beginners starting GLP-1 research", "12–24 weeks"),
            proto(2, "Pen Click Dosing Protocol (60mg/3ml Pen)", "Precise pen-based dosing without syringes.",
                  [{"name": "Tirzepatide 60mg/3ml Pen", "dose": "1 click = 0.25 mg (240 clicks total)"}],
                  ["2.5 mg dose = 10 clicks once weekly (weeks 1–4).",
                   "5 mg dose = 20 clicks (weeks 5–8).",
                   "7.5 mg = 30 clicks; 10 mg = 40 clicks; 12.5 mg = 50 clicks; 15 mg = 60 clicks.",
                   "Store pen at 2–8°C; discard 30 days after first use.",
                   "Rotate injection sites (abdomen, thigh)."],
                  "Pen users seeking precise titration", "12–24 weeks"),
            proto(3, "Metabolic Reset Stack", "Insulin sensitivity and mitochondrial support during weight loss.",
                  [{"name": "Tirzepatide", "dose": "5 mg weekly"},
                   {"name": "MOTS-c", "dose": "10 mg weekly (reconstituted, split 2x/week)"},
                   {"name": "NAD+", "dose": "100 mg SC 2x/week"}],
                  ["Tirzepatide 5 mg SC once weekly (fixed day).",
                   "MOTS-c 5 mg SC Monday and Thursday mornings.",
                   "NAD+ 100 mg SC on training days.",
                   "Combine with resistance training 3x/week to preserve lean mass."],
                  "Metabolic optimization and energy during caloric deficit", "12 weeks"),
            proto(4, "Lean Mass Preservation Stack", "Weight loss while protecting muscle tissue.",
                  [{"name": "Tirzepatide", "dose": "5–7.5 mg weekly"},
                   {"name": "Ipamorelin", "dose": "300 mcg SC before bed"},
                   {"name": "5-Amino-1MQ", "dose": "50 mg capsule daily"}],
                  ["Tirzepatide weekly per titration schedule.",
                   "Ipamorelin 300 mcg SC nightly (empty stomach, 2h after last meal).",
                   "5-Amino-1MQ 50 mg each morning.",
                   "Protein ≥2 g/kg; resistance training mandatory 3–4x/week."],
                  "Preserving muscle during aggressive fat loss phases", "12–16 weeks"),
            proto(5, "Plateau Breaker Protocol", "Restarting progress after weight loss stalls.",
                  [{"name": "Tirzepatide", "dose": "increase current dose by 2.5 mg weekly"},
                   {"name": "SLU-PP-332", "dose": "250 mcg 2x daily, 5 days/week"}],
                  ["Increase Tirzepatide by one titration step (max 15 mg).",
                   "Add SLU-PP-332 250 mcg morning and midday, weekdays only.",
                   "Add 2 fasted LISS cardio sessions weekly.",
                   "Reassess after 4 weeks; hold dose once progress resumes."],
                  "Researchers hitting a weight plateau after 8+ weeks", "4–8 weeks"),
            proto(6, "Maintenance & Taper Protocol", "Sustaining results and preventing rebound after target weight.",
                  [{"name": "Tirzepatide", "dose": "reduce by 2.5 mg every 4 weeks to lowest effective dose"}],
                  ["Reduce dose one step every 4 weeks while monitoring appetite and weight.",
                   "Hold at lowest effective dose (2.5–5 mg) or move to bi-weekly dosing.",
                   "Keep protein high and training consistent through the taper.",
                   "If weight regain >3%, return to previous effective dose."],
                  "Post-goal maintenance and controlled discontinuation", "8–16 weeks"),
        ],
    },
    {
        "slug": "retatrutide", "peptide_slug": "retatrutide", "peptide_name": "Retatrutide",
        "title": "Retatrutide Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "GLP-1 / Metabolic", "category_slug": "glp1-metabolic",
        "classification": "Triple GLP-1/GIP/Glucagon Receptor Agonist",
        "also_known_as": ["LY3437943", "Triple G"],
        "description": "Retatrutide is a triple agonist activating GLP-1, GIP and glucagon receptors. Phase 2 trials showed up to 24.2% body weight reduction — the strongest result ever recorded for an incretin — with added energy-expenditure effects from glucagon activation.",
        "core_info": {
            "function": "Maximum-potency weight reduction, appetite suppression and increased energy expenditure.",
            "typical_dosage": "1–12 mg subcutaneously once weekly (titrated)",
            "administration": "Subcutaneous injection or pre-filled pen (click dosing)",
            "best_timing": "Same day each week",
            "common_cycle": "16–24+ weeks with slow titration",
            "common_pairings": ["Tirzepatide (rotation)", "MOTS-c", "NAD+", "Ipamorelin"],
        },
        "protocols": [
            proto(1, "Conservative Titration Protocol", "Maximum results with controlled side effects via slow ramp.",
                  [{"name": "Retatrutide", "dose": "1–2 mg weekly (weeks 1–4), 4 mg (weeks 5–8), 6–8 mg (weeks 9+), max 12 mg"}],
                  ["Reconstitute 10mg vial with 1 mL bacteriostatic water.",
                   "Weeks 1–4: 2 mg SC weekly (20 units).",
                   "Weeks 5–8: 4 mg weekly (40 units).",
                   "Weeks 9+: 6–8 mg if needed; never exceed 12 mg weekly.",
                   "Monitor heart rate — glucagon activation may raise resting HR slightly."],
                  "Beginners to triple-agonist research", "16–24 weeks"),
            proto(2, "Pen Click Dosing Protocol (40mg/3ml Pen)", "Precise pen-based titration without syringes.",
                  [{"name": "Retatrutide 40mg/3ml Pen", "dose": "1 click = 0.167 mg (240 clicks total)"}],
                  ["2.5 mg dose = 15 clicks once weekly.",
                   "5 mg = 30 clicks; 7.5 mg = 45 clicks; 10 mg = 60 clicks.",
                   "Store pen at 2–8°C; discard 30 days after first use.",
                   "Rotate injection sites weekly."],
                  "Pen users seeking precise weekly titration", "16–24 weeks"),
            proto(3, "Maximum Fat Loss Stack", "Aggressive recomposition combining triple agonism with lipolytics.",
                  [{"name": "Retatrutide", "dose": "4–6 mg weekly"},
                   {"name": "HGH Frag 176-191", "dose": "250 mcg SC 2x daily (fasted)"}],
                  ["Retatrutide weekly per titration.",
                   "HGH Frag 250 mcg on waking (fasted) and pre-cardio.",
                   "Fasted LISS cardio 3–4x weekly.",
                   "Electrolytes daily; reassess bodyfat every 4 weeks."],
                  "Advanced fat loss phases", "12–16 weeks"),
            proto(4, "Energy & Mitochondria Support Stack", "Countering fatigue during deep caloric deficit.",
                  [{"name": "Retatrutide", "dose": "4 mg weekly"},
                   {"name": "NAD+", "dose": "100 mg SC 3x/week"},
                   {"name": "Vitamin B12", "dose": "1,000 mcg SC weekly"}],
                  ["Retatrutide weekly, fixed day.",
                   "NAD+ Monday/Wednesday/Friday mornings.",
                   "B12 1,000 mcg weekly alongside the Retatrutide shot.",
                   "Sleep 7.5h+ — glucagon agonism raises energy demand."],
                  "Energy, focus and vitality during weight loss", "12 weeks"),
            proto(5, "Muscle-Guard Recomp Stack", "Recomposition with GH support to protect lean tissue.",
                  [{"name": "Retatrutide", "dose": "4–6 mg weekly"},
                   {"name": "CJC-1295 + Ipamorelin", "dose": "300/300 mcg SC nightly"}],
                  ["Retatrutide weekly per titration.",
                   "CJC/Ipa blend nightly before bed on empty stomach.",
                   "Protein ≥2 g/kg; heavy compound lifts 3x/week.",
                   "Deload training every 6th week."],
                  "Preserving muscle in long cutting phases", "16 weeks"),
            proto(6, "Post-Cycle Metabolic Consolidation", "Locking in results after a Retatrutide run.",
                  [{"name": "Retatrutide", "dose": "taper: reduce 2 mg every 3 weeks"},
                   {"name": "MOTS-c", "dose": "10 mg weekly"},
                   {"name": "5-Amino-1MQ", "dose": "50 mg daily"}],
                  ["Taper Retatrutide by 2 mg every 3 weeks until 2 mg, then stop.",
                   "Start MOTS-c and 5-Amino-1MQ in the final taper month and run 8 more weeks.",
                   "Increase daily steps to 10k+ to defend the new set point."],
                  "Preventing rebound after discontinuation", "10–14 weeks"),
        ],
    },
    {
        "slug": "glow-blend", "peptide_slug": "glow-blend", "peptide_name": "Glow Blend",
        "title": "Glow Blend Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Skin / Regeneration", "category_slug": "skin-regeneration",
        "classification": "GHK-Cu 50mg + BPC-157 10mg + TB-500 10mg Combination",
        "also_known_as": ["Glow 70", "Beauty Blend"],
        "description": "Glow Blend is Zurix's exclusive 3-in-1 formula combining GHK-Cu (collagen induction), BPC-157 (tissue repair) and TB-500 (regeneration). Researched for skin rejuvenation, firmness, wound healing and whole-body recovery.",
        "core_info": {
            "function": "Skin rejuvenation, collagen synthesis, tissue repair and systemic recovery.",
            "typical_dosage": "Dosed by GHK-Cu content: 1–2 mg daily",
            "administration": "Subcutaneous injection or pre-filled pen (click dosing)",
            "best_timing": "Evening, before bed",
            "common_cycle": "6–8 weeks on, 4 weeks off",
            "common_pairings": ["Glutathione", "Epithalon", "KPV", "AHK-Cu"],
        },
        "protocols": [
            proto(1, "Beginner Glow Protocol", "Introduction to skin rejuvenation dosing.",
                  [{"name": "Glow Blend", "dose": "1 mg GHK-Cu equivalent daily (vial: reconstitute 70mg with 2 mL; inject 4 units)"}],
                  ["Reconstitute 70mg vial with 2 mL bacteriostatic water.",
                   "Inject 4 units (0.04 mL) SC nightly — delivers ~1 mg GHK-Cu + 0.2 mg BPC-157 + 0.2 mg TB-500.",
                   "Inject into abdomen or area of concern (facial-adjacent SC for skin focus).",
                   "Run 6 weeks, then 4 weeks off."],
                  "First-time users of copper peptide blends", "6 weeks"),
            proto(2, "Pen Click Dosing Protocol (70mg/3ml Pen)", "Standard site-protocol dosing via pen clicks.",
                  [{"name": "Glow Blend 70mg/3ml Pen", "dose": "1 click = 0.292 mg blend (0.208 mg GHK-Cu)"}],
                  ["Beginner dose 1 mg GHK-Cu = 5 clicks nightly (~48 doses per pen).",
                   "Standard dose 2 mg GHK-Cu = 10 clicks nightly (~24 doses per pen).",
                   "Store pen at 2–8°C; discard 30 days after first use.",
                   "Rotate injection sites; avoid injecting the same spot twice in 48h."],
                  "Pen users following the standard site protocols", "6–8 weeks"),
            proto(3, "Total Skin Rejuvenation Stack", "Maximum collagen, luminosity and skin quality.",
                  [{"name": "Glow Blend", "dose": "2 mg GHK-Cu equivalent nightly"},
                   {"name": "Glutathione", "dose": "200 mg SC 2x/week"},
                   {"name": "Epithalon", "dose": "5 mg SC daily for first 20 days"}],
                  ["Glow Blend nightly (10 clicks pen or 8 units vial solution).",
                   "Glutathione Monday/Thursday mornings.",
                   "Epithalon daily only during the first 20 days of the cycle.",
                   "SPF 50 daily — copper peptides increase skin turnover."],
                  "Anti-aging and luminosity focus", "8 weeks"),
            proto(4, "Post-Procedure Recovery Protocol", "Accelerated healing after microneedling, laser or peels.",
                  [{"name": "Glow Blend", "dose": "2 mg GHK-Cu equivalent daily"},
                   {"name": "KPV", "dose": "250 mcg SC daily"}],
                  ["Start 48h after the procedure (never on broken skin day).",
                   "Glow Blend nightly for 14 days.",
                   "KPV each morning for inflammation control.",
                   "Avoid retinoids and acids during the 14-day window."],
                  "Recovery windows after aesthetic procedures", "2–3 weeks per procedure"),
            proto(5, "Hair & Skin Synergy Stack", "Combined skin quality and hair density approach.",
                  [{"name": "Glow Blend", "dose": "1–2 mg GHK-Cu equivalent nightly"},
                   {"name": "AHK-Cu", "dose": "1 mg SC into scalp-adjacent sites 3x/week"}],
                  ["Glow Blend nightly per standard dosing.",
                   "AHK-Cu Monday/Wednesday/Friday.",
                   "Optional: dermaroller 0.5 mm weekly on scalp (not same day as injections).",
                   "Photograph progress every 2 weeks."],
                  "Skin + hair combined goals", "8–12 weeks"),
            proto(6, "Joint & Skin Recovery Stack", "Leveraging the BPC/TB content for connective tissue.",
                  [{"name": "Glow Blend", "dose": "2 mg GHK-Cu equivalent daily"},
                   {"name": "BPC-157", "dose": "250 mcg SC daily near affected joint"}],
                  ["Glow Blend nightly (systemic).",
                   "Additional BPC-157 250 mcg SC as close to the affected joint as practical.",
                   "Light mobility work daily; avoid maximal loading for first 3 weeks."],
                  "Skin goals with concurrent joint/tendon complaints", "6–8 weeks"),
        ],
    },
    {
        "slug": "vitamin-b12", "peptide_slug": "vitamin-b12", "peptide_name": "Vitamin B12",
        "title": "Vitamin B12 Stack Library", "subtitle": "Premium Protocol Collection",
        "category": "Vitamins / Wellness", "category_slug": "vitamins-wellness",
        "classification": "Cyanocobalamin 10,000 mcg/mL Solution",
        "also_known_as": ["Cyanocobalamin", "Cobalamin"],
        "description": "High-concentration Vitamin B12 (cyanocobalamin) researched for energy metabolism, red blood cell formation, neurological function and homocysteine regulation. Injectable delivery bypasses intestinal absorption limits, achieving full bioavailability.",
        "core_info": {
            "function": "Energy metabolism, nervous system support, red blood cell production.",
            "typical_dosage": "500–1,000 mcg SC/IM, 1–2x weekly",
            "administration": "Subcutaneous or intramuscular injection",
            "best_timing": "Morning (can be mildly energizing)",
            "common_cycle": "Continuous or 8–12 week blocks",
            "common_pairings": ["NAD+", "Glutathione", "MOTS-c", "GLP-1 protocols"],
        },
        "protocols": [
            proto(1, "Energy Restoration Protocol", "Correcting fatigue and low energy availability.",
                  [{"name": "Vitamin B12", "dose": "1,000 mcg (0.1 mL) SC 2x/week for 4 weeks, then 1x/week"}],
                  ["Draw 0.1 mL (10 units) of the 10,000 mcg/mL solution.",
                   "Inject SC morning, Monday and Thursday, for 4 weeks.",
                   "Maintenance: 1,000 mcg once weekly.",
                   "Store vial at 2–8°C protected from light."],
                  "Fatigue, low energy, vegetarians/vegans", "8–12 weeks"),
            proto(2, "GLP-1 Companion Protocol", "Preventing B12 depletion during appetite-suppressed phases.",
                  [{"name": "Vitamin B12", "dose": "1,000 mcg SC weekly"},
                   {"name": "Tirzepatide or Retatrutide", "dose": "per ongoing protocol"}],
                  ["Inject B12 the same day as the weekly GLP-1 dose.",
                   "Reduced food intake on GLP-1s lowers B12 intake — supplementation offsets it.",
                   "Continue for the full duration of the GLP-1 protocol."],
                  "Anyone running GLP-1 weight loss protocols", "Duration of GLP-1 cycle"),
            proto(3, "Cognitive & Mood Support Stack", "Neurological support and mental clarity.",
                  [{"name": "Vitamin B12", "dose": "1,000 mcg SC weekly"},
                   {"name": "NAD+", "dose": "100 mg SC 2x/week"},
                   {"name": "Semax", "dose": "300 mcg intranasal daily"}],
                  ["B12 Monday morning.",
                   "NAD+ Tuesday and Friday mornings.",
                   "Semax daily on workdays.",
                   "Assess focus/mood at week 4."],
                  "Mental clarity, mood and nervous system support", "8 weeks"),
            proto(4, "Metabolic Energy Stack", "Mitochondrial and methylation support for training phases.",
                  [{"name": "Vitamin B12", "dose": "500 mcg SC 2x/week"},
                   {"name": "MOTS-c", "dose": "5 mg SC 2x/week"}],
                  ["B12 + MOTS-c on the same mornings (Mon/Thu), separate syringes.",
                   "Time on training days for perceived energy benefit.",
                   "Hydration ≥3L; monitor training output weekly."],
                  "Athletes and high-output training blocks", "8–12 weeks"),
            proto(5, "Deficiency Correction Protocol", "Aggressive repletion for documented low B12.",
                  [{"name": "Vitamin B12", "dose": "1,000 mcg IM every other day for 2 weeks, then weekly"}],
                  ["1,000 mcg IM every 48h for 2 weeks (7 injections).",
                   "Then 1,000 mcg weekly for 8 weeks.",
                   "Retest serum B12 and homocysteine at week 10.",
                   "Continue monthly maintenance if levels stabilize."],
                  "Documented deficiency states (research setting)", "10–12 weeks"),
        ],
    },
]


async def main():
    db = AsyncIOMotorClient(os.environ["MONGO_URL"])[os.environ["DB_NAME"]]
    for hub in HUBS:
        existing = await db.stack_hubs.find_one({"slug": hub["slug"]}, {"_id": 1})
        await db.stack_hubs.replace_one({"slug": hub["slug"]}, hub, upsert=True)
        print(f"{'updated' if existing else 'created'}: {hub['slug']} ({len(hub['protocols'])} protocols)")
    total = await db.stack_hubs.count_documents({})
    print("total hubs:", total)

asyncio.run(main())
